name: run all jobs
on: push

jobs:
  verify-migration-proofs:
    uses: ./.github/workflows/migration.yml

  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml