name: run all jobs
on: push

jobs:
  migration:
    uses: ./.github/workflows/migration.yml

  # TODO tmp disable
#  lint:
#    uses: ./.github/workflows/lint.yml
#
#  test:
#    uses: ./.github/workflows/test.yml