name: migration
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Check out repository code
        uses: actions/checkout@v4
      # Setup Python
      - name: Install dependencies
        run: pip3 install bech32 requests
      - name: Verify migration proofs
        working-directory: ./app/upgrades/v2_0/validator-proofs
        run: python3 verify.py